### ISSUE TITLE
Submit link failed

### ISSUE THREAD

**Issue by PetWorm** [uzh-rpg/IROS2020-FPV-VIO-Competition#2]
hi, it seems that the submit link has failed.

**Comment by tcies** [comment]
Sorry for the late reply. Unfortunately, I was not able to reproduce the failure, just made a successful test submission. The form is here: https://form.jotform.com/201473389108356

**Comment by PetWorm** [comment]
Thanks, it just somehow can be opened right now. I'll close this.

**Comment by tcies** [comment]
We just figured out what happened: There are two submission links in the Readme, but only one of them was updated to the IROS competition. Sorry about that.
