### ISSUE TITLE
Do not find my competetion result.

### ISSUE THREAD

**Issue by glxin1982** [uzh-rpg/IROS2020-FPV-VIO-Competition#7]
I have commit my data to IROS2020-FPV-VIO-Competition at 2020/09/23
and recieved the feedback mail like this:

Team name | Lenovo_LR_ShangHai
-- | --
Team Correspondent | LiXin Gao
Affiliation | Lenovo Research ShangHai
Contact e-mail | gaolx2@lenovo.com
Indoor forward 11 | indoor_forward_11_snapdragon.txt
Indoor forward 12 | indoor_forward_12_snapdragon.txt
Indoor 45deg 3 | indoor_45_3_snapdragon.txt
Indoor 45deg 16 | indoor_45_16_snapdragon.txt
Outdoor forward 9 | outdoor_forward_9_snapdragon.txt
Outdoor forward 10 | outdoor_forward_10_snapdragon.txt
Report | SLAM-OB for FPV VIO Competition IROS2020.pdf

But I do not find evaluation result on the web https://fpv.ifi.uzh.ch/?sourcenova-comp-post=2019-2020-uzh-fpv-benchmark.
And my account can not login either.
Is there something wrong? Or not all the result will be public?

**Comment by tcies** [comment]
See e-mail. I'm very sorry about that!
